options {
	STATIC = false;
}

PARSER_BEGIN(Calculator)
package be.fedict.eid.applet.tests.javacc.calc;

import java.io.PrintStream;
	
public class Calculator {
	static void main(String[] args) throws ParseException, TokenMgrError, NumberFormatException {
		Calculator parser = new Calculator(System.in);
		parser.Start(System.out);
	}
	double previousValue = 0.0;
}
PARSER_END(Calculator)

SKIP : { " " }
TOKEN : { < EOL : "\n" | "\r" | "\r\n" > }
TOKEN : { < PLUS : "+" > }

TOKEN : { < NUMBER : <DIGITS> | <DIGITS> "." <DIGITS> | <DIGITS> "." | "." <DIGITS> > }
TOKEN : { < #DIGITS : (["0"-"9"])+ > }

void Start(PrintStream printStream) throws NumberFormatException :
{}
{
	(
		previousValue = Expression()
		<EOL>
		{ printStream.println(previousValue); }
	)*
	<EOF>
}

double Expression() throws NumberFormatException :
{
	double i;
	double value;
}
{
	value = Primary()
	(
		<PLUS>
		i = Primary()
		{ value += i; }
	)*
	{ return value; }
}

double Primary() throws NumberFormatException :
{
	Token t;
}
{
	t = <NUMBER>
	{ return Double.parseDouble(t.image); }
}